### ISSUE TITLE
name 'plate' is used prior to global declaration

### ISSUE THREAD

**Issue by AmonB** [marcottelab/appaloosa#1]
Hello, I have a problem when running ./analyze_tlc.py and I'm using python3 to run. Could you please tell me how to fix this problem.
![image](https://user-images.githubusercontent.com/64903539/89122511-3b4c7380-d4fa-11ea-97ed-63a834c129eb.png)

**Comment by alexanderboulgakov** [comment]
Hi Amon, this is made for Python 2, which will throw a syntax warning but
will still run the program.
